#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${MOONBASE:-$HOME}/.moonbase/init.zsh" ]]; then
  source "${MOONBASE:-$HOME}/.moonbase/init.zsh"
fi

if [[ -s "${MOONBASE:-$HOME}/.moonbase/modules/syntax-highlighting/external/zsh-syntax-highlighting.zsh" ]]; then
   source "${MOONBASE:-$HOME}/.moonbase/modules/syntax-highlighting/external/zsh-syntax-highlighting.zsh"
fi

if [[ -d "$HOME/.rvm/bin" ]]; then
  export PATH="$PATH:$HOME/.rvm/bin"
fi

export hst=$(hostname -s)

